[phases.setup]
  nixPkgs = ['nodejs_18', 'python3']

[phases.install]
  cmds = ['pip install -r requirements.txt']

[phases.build]
  cmds = []

[phases.start]
  cmd = 'gunicorn app_streaming:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120' 