[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app_streaming:app --bind 0.0.0.0:$PORT --workers 1 --timeout 600 --keep-alive 65 --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3